goal: ""

llm_providers:
  openai:
    kind: openai
    base_url: ${OPENAI_BASE_URL}
    api_key_env: OPENAI_API_KEY
  cesnet:
    kind: openai
    base_url: ${CESNET_BASE_URL}
    api_key_env: CESNET_API_KEY
  cesnet_interpreter:
    kind: openai
    base_url: ${CESNET_BASE_URL}
    api_key_env: CESNET_API_KEY
  ollama:
    kind: ollama
    host: ${OLLAMA_HOST}
    port: ${OLLAMA_PORT}

targets:
  trident_compromised:
    host: ${SSH_HOST}
    port: ${SSH_PORT}
    user: ${SSH_USER}
    password: ${SSH_PASSWORD}

default_target: trident_compromised

planner_source: ${PLANNER_SOURCE}
planner_model: ${PLANNER_MODEL}

summarizing: false
summarizer_source: ${SUMMARIZER_SOURCE}
summarizer_model: ${SUMMARIZER_MODEL}

interpreter_source: ${INTERPRETER_SOURCE}
interpreter_model: ${INTERPRETER_MODEL}

action_limit: 50
